### ISSUE TITLE
FirefoxOS: control A2DB connexion

### ISSUE THREAD

**Issue by jbruggem** [mozilla/high-fidelity#41]
When I'm listening to a podcast using my car speakers (connected using A2DP to my phone), the music application interferes with HF: play events are triggered when:
- the connexion is established
- the car's sound volume is changed
I then have to manually stop the music player on FxOS to continue listening to my podcast.

Additionally, it would be great if the play/pause button of the car could play/pause HF.

(Bluetooth API seem to require a certified app, unfortunately.)

**Comment by tofumatt** [comment]
We've rethought the direction of the app; anything requiring packaged/certified Firefox OS APIs isn't going to be implemented.
