### ISSUE TITLE
Make media player bigger

### ISSUE THREAD

**Issue by mcepl** [mozilla/high-fidelity#44]
Not everybody is twenty with eagle-sharp eyes. https://github.com/thasmin/Podax on Android has actually a special tab (aside from "All my podcasts", "Search for new podcast", and "Current queue" ones) with a media player. [Its Android appstore page](https://play.google.com/store/apps/details?id=com.axelby.podax) shows it pretty nicely.

**Comment by tofumatt** [comment]
Closing as we'll be fixing up the codebase and want to keep the issues here for the new version we're working on.
