### ISSUE TITLE
wreong

### ISSUE THREAD

**Issue by mcepl** [mozilla/high-fidelity#62]
When doing `npm install` I get among other messages also:
```
npm http 200 https://registry.npmjs.org/grunt-jscs-checker
npm WARN deprecated grunt-jscs-checker@0.4.4: Package was renamed to 'grunt-jscs'
```

**Comment by tofumatt** [comment]
Should be a matter of updating the package.json here, did you get any other warnings I should take a look at?

- tofumatt (Sent from mobile)

On 5 April 2015 01:31:51 EEST, Matěj Cepl <notifications@github.com> wrote:When doing npm install  I get among other messages also:  npm http 200 https://registry.npmjs.org/grunt-jscs-checker npm WARN deprecated grunt-jscs-checker@0.4.4: Package was renamed to 'grunt-jscs'    —Reply to this email directly or view it on GitHub.

**Comment by mcepl** [comment]
I think, that's it:
```
matej@mitmanek: high-fidelity (master %)$ grep -E -i '(warn|err)' npm-log.txt 
npm WARN package.json high-fidelity@2.0.1 No repository field.
npm WARN deprecated grunt-jscs-checker@0.4.4: Package was renamed to 'grunt-jscs'
matej@mitmanek: high-fidelity (master %)$ 
```

**Comment by tofumatt** [comment]
Closing as we'll be fixing up the codebase and want to keep the issues here for the new version we're working on.
