### ISSUE TITLE
Merge with ember-cli version?

### ISSUE THREAD

**Issue by brittanystoroz** [mozilla/high-fidelity#65]
Do we want to convert this to ember-cli? Haven't looked at how many commits back I did that, but ember-cli version is here: https://github.com/brittanystoroz/its-five-o-clock-somewhere. There might be some annoying manual updates depending on how much has gone on with this app since then, and it's probably in dire need of dependency updates.

Just something to think about before we try adding in service workers. Might be good for people to see a SW example in an app using a popular framework.

**Comment by tofumatt** [comment]
I'd love for it to be an actual Ember CLI app, so even if there are annoying manual things to do I say it's worth it. Maybe even just manually moving over the app/ files into a new Ember CLI app would work if there's too much manual mucking about?



- tofumatt

**Comment by brittanystoroz** [comment]
Lol I totally posted the wrong link earlier...that's the timezone app not the podcasts app. I do believe I converted podcasts to ember-cli but may not have put it up on github. Will check on this tomorrow. Regardless, it's something I can take care of if I haven't already ¯\_(ツ)_/¯

**Comment by brittanystoroz** [comment]
closing this - ember-cli-conversion branch has been added to the repo and will work on related bugs there
