### ISSUE TITLE
Need Ember bugfix for major jQuery assertion error

### ISSUE THREAD

**Issue by kriscooke** [mozilla/high-fidelity#94]
Newcomers doing `bower install` currently resolve to jQuery 1.12; in [emberjs/ember.js](https://github.com/rwjblue/ember.js/commit/a9ac424d86ebd472f48abd736cb20dccff991d7b) there is a silly jQuery detection assert error right in the framework loading sequence, resulting in a major fail as Ember cannot finish loading. 

Without the bugfix, [Ember apps with jQuery > 1.11 fail without even being able to load their app](ember-cli/ember-cli#5316). Indeed, I couldn't even run the tests on master. This results in a confusing error message, since 1.12 should be just fine (and of course it is):

```Uncaught Error: Assertion Failed: Ember Views require jQuery between 1.7 and 2.1```

This is fixed in [emberjs/ember.js v1.13.13](https://github.com/emberjs/ember.js/blob/a3e5bb96b9241c56e66cb6d749ecd644d7b113bf/CHANGELOG.md), and resolved by PR #93 .

**Comment by tofumatt** [comment]
Fixed by #93.
